// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace FrameWork {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class VerifyProtocolReplyProto {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    internal static pbd::MessageDescriptor internal__static_login_proto_VerifyProtocolReply__Descriptor;
    internal static pb::FieldAccess.FieldAccessorTable<global::FrameWork.VerifyProtocolReply, global::FrameWork.VerifyProtocolReply.Builder> internal__static_login_proto_VerifyProtocolReply__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static VerifyProtocolReplyProto() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "Ch13YXIvVmVyaWZ5UHJvdG9jb2xSZXBseS5wcm90bxILbG9naW4ucHJvdG8a" + 
          "JGdvb2dsZS9wcm90b2J1Zi9jc2hhcnBfb3B0aW9ucy5wcm90byKwAwoTVmVy" + 
          "aWZ5UHJvdG9jb2xSZXBseRJACgtyZXN1bHRfY29kZRgBIAIoDjIrLmxvZ2lu" + 
          "LnByb3RvLlZlcmlmeVByb3RvY29sUmVwbHkuUmVzdWx0Q29kZRILCgNpdjEY" + 
          "AiABKAwSCwoDaXYyGAMgASgMIrwCCgpSZXN1bHRDb2RlEg8KC1JFU19TVUND" + 
          "RVNTEAASHAoYUkVTX1BST1RPQ09MX1VOU1VQUE9SVEVEEAESGwoXUkVTX1BS" + 
          "T0RVQ1RfVU5TVVBQT1JURUQQAhIbChdSRVNfQUNDT1VOVF9BVVRIX0ZBSUxF" + 
          "RBADEhoKFlJFU19BQ0NPVU5UX1RFUk1JTkFURUQQBBIXChNSRVNfQUNDT1VO" + 
          "VF9FWFBJUkVEEAUSGQoVUkVTX0FDQ09VTlRfU1VTUEVOREVEEAYSJQohUkVT" + 
          "X0FDQ09VTlRfU0VDT05EQVJZX0FVVEhfTkVFREVEEAcSHgoaUkVTX0FDQ09V" + 
          "TlRfQUxSRUFEWV9PTkxJTkUQCBIUChBSRVNfU1lTVEVNX0VSUk9SEAkSGAoU" + 
          "UkVTX0VOQ1JZUFRJT05fRVJST1IQCkIowj4lCglGcmFtZVdvcmsSGFZlcmlm" + 
          "eVByb3RvY29sUmVwbHlQcm90bw==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_login_proto_VerifyProtocolReply__Descriptor = Descriptor.MessageTypes[0];
        internal__static_login_proto_VerifyProtocolReply__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::FrameWork.VerifyProtocolReply, global::FrameWork.VerifyProtocolReply.Builder>(internal__static_login_proto_VerifyProtocolReply__Descriptor,
                new string[] { "ResultCode", "Iv1", "Iv2", });
        pb::ExtensionRegistry registry = pb::ExtensionRegistry.CreateInstance();
        RegisterAllExtensions(registry);
        global::Google.ProtocolBuffers.DescriptorProtos.CSharpOptions.RegisterAllExtensions(registry);
        return registry;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          global::Google.ProtocolBuffers.DescriptorProtos.CSharpOptions.Descriptor, 
          }, assigner);
    }
    #endregion
    
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class VerifyProtocolReply : pb::GeneratedMessage<VerifyProtocolReply, VerifyProtocolReply.Builder> {
    private VerifyProtocolReply() { }
    private static readonly VerifyProtocolReply defaultInstance = new VerifyProtocolReply().MakeReadOnly();
    private static readonly string[] _verifyProtocolReplyFieldNames = new string[] { "iv1", "iv2", "result_code" };
    private static readonly uint[] _verifyProtocolReplyFieldTags = new uint[] { 18, 26, 8 };
    public static VerifyProtocolReply DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override VerifyProtocolReply DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override VerifyProtocolReply ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::FrameWork.VerifyProtocolReplyProto.internal__static_login_proto_VerifyProtocolReply__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<VerifyProtocolReply, VerifyProtocolReply.Builder> InternalFieldAccessors {
      get { return global::FrameWork.VerifyProtocolReplyProto.internal__static_login_proto_VerifyProtocolReply__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum ResultCode {
        RES_SUCCESS = 0,
        RES_PROTOCOL_UNSUPPORTED = 1,
        RES_PRODUCT_UNSUPPORTED = 2,
        RES_ACCOUNT_AUTH_FAILED = 3,
        RES_ACCOUNT_TERMINATED = 4,
        RES_ACCOUNT_EXPIRED = 5,
        RES_ACCOUNT_SUSPENDED = 6,
        RES_ACCOUNT_SECONDARY_AUTH_NEEDED = 7,
        RES_ACCOUNT_ALREADY_ONLINE = 8,
        RES_SYSTEM_ERROR = 9,
        RES_ENCRYPTION_ERROR = 10,
      }
      
    }
    #endregion
    
    public const int ResultCodeFieldNumber = 1;
    private bool hasResultCode;
    private global::FrameWork.VerifyProtocolReply.Types.ResultCode resultCode_ = global::FrameWork.VerifyProtocolReply.Types.ResultCode.RES_SUCCESS;
    public bool HasResultCode {
      get { return hasResultCode; }
    }
    public global::FrameWork.VerifyProtocolReply.Types.ResultCode ResultCode {
      get { return resultCode_; }
    }
    
    public const int Iv1FieldNumber = 2;
    private bool hasIv1;
    private pb::ByteString iv1_ = pb::ByteString.Empty;
    public bool HasIv1 {
      get { return hasIv1; }
    }
    public pb::ByteString Iv1 {
      get { return iv1_; }
    }
    
    public const int Iv2FieldNumber = 3;
    private bool hasIv2;
    private pb::ByteString iv2_ = pb::ByteString.Empty;
    public bool HasIv2 {
      get { return hasIv2; }
    }
    public pb::ByteString Iv2 {
      get { return iv2_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasResultCode) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _verifyProtocolReplyFieldNames;
      if (hasResultCode) {
        output.WriteEnum(1, field_names[2], (int) ResultCode, ResultCode);
      }
      if (hasIv1) {
        output.WriteBytes(2, field_names[0], Iv1);
      }
      if (hasIv2) {
        output.WriteBytes(3, field_names[1], Iv2);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasResultCode) {
          size += pb::CodedOutputStream.ComputeEnumSize(1, (int) ResultCode);
        }
        if (hasIv1) {
          size += pb::CodedOutputStream.ComputeBytesSize(2, Iv1);
        }
        if (hasIv2) {
          size += pb::CodedOutputStream.ComputeBytesSize(3, Iv2);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static VerifyProtocolReply ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static VerifyProtocolReply ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static VerifyProtocolReply ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static VerifyProtocolReply ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private VerifyProtocolReply MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(VerifyProtocolReply prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<VerifyProtocolReply, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(VerifyProtocolReply cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private VerifyProtocolReply result;
      
      private VerifyProtocolReply PrepareBuilder() {
        if (resultIsReadOnly) {
          VerifyProtocolReply original = result;
          result = new VerifyProtocolReply();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override VerifyProtocolReply MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::FrameWork.VerifyProtocolReply.Descriptor; }
      }
      
      public override VerifyProtocolReply DefaultInstanceForType {
        get { return global::FrameWork.VerifyProtocolReply.DefaultInstance; }
      }
      
      public override VerifyProtocolReply BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is VerifyProtocolReply) {
          return MergeFrom((VerifyProtocolReply) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(VerifyProtocolReply other) {
        if (other == global::FrameWork.VerifyProtocolReply.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasResultCode) {
          ResultCode = other.ResultCode;
        }
        if (other.HasIv1) {
          Iv1 = other.Iv1;
        }
        if (other.HasIv2) {
          Iv2 = other.Iv2;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_verifyProtocolReplyFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _verifyProtocolReplyFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              object unknown;
              if(input.ReadEnum(ref result.resultCode_, out unknown)) {
                result.hasResultCode = true;
              } else if(unknown is int) {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                unknownFields.MergeVarintField(1, (ulong)(int)unknown);
              }
              break;
            }
            case 18: {
              result.hasIv1 = input.ReadBytes(ref result.iv1_);
              break;
            }
            case 26: {
              result.hasIv2 = input.ReadBytes(ref result.iv2_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasResultCode {
       get { return result.hasResultCode; }
      }
      public global::FrameWork.VerifyProtocolReply.Types.ResultCode ResultCode {
        get { return result.ResultCode; }
        set { SetResultCode(value); }
      }
      public Builder SetResultCode(global::FrameWork.VerifyProtocolReply.Types.ResultCode value) {
        PrepareBuilder();
        result.hasResultCode = true;
        result.resultCode_ = value;
        return this;
      }
      public Builder ClearResultCode() {
        PrepareBuilder();
        result.hasResultCode = false;
        result.resultCode_ = global::FrameWork.VerifyProtocolReply.Types.ResultCode.RES_SUCCESS;
        return this;
      }
      
      public bool HasIv1 {
        get { return result.hasIv1; }
      }
      public pb::ByteString Iv1 {
        get { return result.Iv1; }
        set { SetIv1(value); }
      }
      public Builder SetIv1(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasIv1 = true;
        result.iv1_ = value;
        return this;
      }
      public Builder ClearIv1() {
        PrepareBuilder();
        result.hasIv1 = false;
        result.iv1_ = pb::ByteString.Empty;
        return this;
      }
      
      public bool HasIv2 {
        get { return result.hasIv2; }
      }
      public pb::ByteString Iv2 {
        get { return result.Iv2; }
        set { SetIv2(value); }
      }
      public Builder SetIv2(pb::ByteString value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasIv2 = true;
        result.iv2_ = value;
        return this;
      }
      public Builder ClearIv2() {
        PrepareBuilder();
        result.hasIv2 = false;
        result.iv2_ = pb::ByteString.Empty;
        return this;
      }
    }
    static VerifyProtocolReply() {
      object.ReferenceEquals(global::FrameWork.VerifyProtocolReplyProto.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
